name: HealthChecks AzureAppConfiguration DB CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - src/HealthChecks.AzureAppConfiguration/**
      - test/HealthChecks.AzureAppConfiguration.Tests/**
      - .github/workflows/healthchecks_azureappconfiguration_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
    tags-ignore:
      - release-*

  pull_request:
    branches: [master]
    paths:
      - src/HealthChecks.AzureAppConfiguration/**
      - test/HealthChecks.AzureAppConfiguration.Tests/**
      - .github/workflows/healthchecks_azureappconfiguration_ci.yml
      - Directory.Build.props
      - Directory.Build.targets
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: false
      - name: Restore
        run: |
          dotnet restore ./src/HealthChecks.AzureAppConfiguration/HealthChecks.AzureAppConfiguration.csproj &&
          dotnet restore ./test/HealthChecks.AzureAppConfiguration.Tests/HealthChecks.AzureAppConfiguration.Tests.csproj
      - name: Check formatting
        run: |
          dotnet format --no-restore --verify-no-changes --severity warn ./src/HealthChecks.AzureAppConfiguration/HealthChecks.AzureAppConfiguration.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1) &&
          dotnet format --no-restore --verify-no-changes --severity warn ./test/HealthChecks.AzureAppConfiguration.Tests/HealthChecks.AzureAppConfiguration.Tests.csproj || (echo "Run 'dotnet format' to fix issues" && exit 1)
      - name: Build
        run: |
          dotnet build --no-restore ./src/HealthChecks.AzureAppConfiguration/HealthChecks.AzureAppConfiguration.csproj
          dotnet build --no-restore ./test/HealthChecks.AzureAppConfiguration.Tests/HealthChecks.AzureAppConfiguration.Tests.csproj
      - name: Test
        run: dotnet test --no-restore --no-build ./test/HealthChecks.AzureAppConfiguration.Tests/HealthChecks.AzureAppConfiguration.Tests.csproj
